{
 "title": "IT Supervision - Jobs and Pipelines",
 "description": "Saagie Jobs and Pipelines duration and status",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project Name",
    "query": "select distinct project_name as\"__text\", project_id as \"__value\" from supervision_saagie"
   }
  ]
 },
 "panels": [
  {
   "title": "Status Job Evolution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "% of instances" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date(instance_start_time) AS \"time\",\n  instance_status as \"metric\",\n  count(*) AS \"value\"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_start_time)\n  and orchestration_type='job'\n  and project_id='$project'\n  group by time, metric\n  order by time, metric\n \n  \n"
    }
   ]
  },
  {
   "title": "Jobs duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_start_time AS \"time\",\n  orchestration_name as \"metric\",\n  instance_duration AS \"value\"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_start_time)\n  and orchestration_type='job'\n  and project_id='$project'\n"
    }
   ]
  },
  {
   "title": "Pipelines duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  instance_start_time AS \"time\",\n  orchestration_name as \"metric\",\n  instance_duration AS \"value\"\nFROM supervision_saagie\nWHERE\n  $__timeFilter(instance_start_time)\n  and orchestration_type='pipeline'\n  and project_id='$project'"
    }
   ]
  },
  {
   "title": "Longest jobs",
   "type": "table",
   "description": "Based on their last instance",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT instance_duration,orchestration_name,instance_start_time, instance_end_time, instance_status, instance_saagie_url FROM supervision_saagie a\nwhere orchestration_type='job'\nand project_id='$project'\nand instance_start_time = (select max(instance_start_time) from supervision_saagie b\nwhere orchestration_type='job' and a.orchestration_id = b.orchestration_id)\nORDER BY instance_duration DESC\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Failure ratio",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n    \n    CAST((SELECT COUNT(*) FROM supervision_saagie t2 WHERE t1.orchestration_id = t2.orchestration_id and  instance_status != 'SUCCEEDED') AS DECIMAL) / \n    CAST((SELECT COUNT(*) FROM supervision_saagie t2 WHERE t1.orchestration_id = t2.orchestration_id ) AS DECIMAL)*100 AS \"Failure Ratio\",\n    orchestration_name as \"Job Name\", \n\t(SELECT COUNT (*) FROM supervision_saagie t2 WHERE t1.orchestration_id = t2.orchestration_id and instance_status = 'SUCCEEDED') AS \"Success\",\n\t(SELECT COUNT (*) FROM supervision_saagie t2 WHERE t1.orchestration_id = t2.orchestration_id and instance_status != 'SUCCEEDED') AS \"Failed\"\n\tFROM supervision_saagie t1 \n\twhere project_id='$project'\n\tgroup by orchestration_id,orchestration_name\norder by 1 DESC"
    }
   ]
  }
 ]
}