schemaVersion: "2.0.0"

metadataTest:
  env:
    - key: LANG
      value: "en_US.UTF-8"
    - key: LC_ALL
      value: "en_US.UTF-8"

fileExistenceTests:
  - name: "entrypoint"
    path: "/entrypoint.sh"
    shouldExist: true
    permissions: "-rwxr-xr-x"

  - name: "server.conf"
    path: "/etc/nginx/sites-enabled/grafana.conf"
    shouldExist: true
    permissions: "-rwxr-xr-x"

  - name: "grafana.ini"
    path: "/etc/grafana/grafana.ini"
    shouldExist: true
    permissions: "-rwxr-xr-x"

