{
 "title": "S3 - Global Usage",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total space used",
   "type": "stat",
   "description": "Space used by all s3 buckets",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n  supervision_date AS \"time\",\n  supervision_value AS \"value\"\nFROM supervision_s3 a\nWHERE $__timeFilter(supervision_date)\nAND supervision_label ='bucket_size' \nand supervision_namespace='all_buckets'\n\n"
    }
   ]
  },
  {
   "title": "Total # of objects",
   "type": "stat",
   "description": "Number of objects across all s3 buckets",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT distinct\n  supervision_date AS \"time\",\n  supervision_value AS \"value\"\nFROM supervision_s3 a\nWHERE $__timeFilter(supervision_date)\nAND supervision_label ='bucket_objects' \nand supervision_namespace='all_buckets'\n\n"
    }
   ]
  },
  {
   "title": "Buckets size",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  supervision_namespace as \"Bucket\",\n  supervision_value as \"Size\"\nFROM\n  supervision_s3 a\nWHERE \n  supervision_label='bucket_size'\n  and supervision_namespace<>'all_buckets'\n  and supervision_date=(SELECT max(supervision_date) from supervision_s3 b where a.supervision_label=b.supervision_label)\n\n"
    }
   ]
  },
  {
   "title": "Bucket size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  supervision_date AS \"time\",\n  supervision_namespace as \"metric\",\n  supervision_value AS \"value\"\nFROM supervision_s3\nWHERE\n  $__timeFilter(supervision_date)\n  AND supervision_label ='bucket_size'\n  AND supervision_namespace <>'all_buckets'\nGROUP BY supervision_date, supervision_namespace,supervision_value\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT distinct\n  supervision_date AS \"time\",\n  'total available size' as \"metric\",\n  2500 AS \"value\"\nFROM supervision_s3\nWHERE\n  $__timeFilter(supervision_date)\n  AND supervision_label ='bucket_size'\nGROUP BY supervision_date, supervision_namespace,supervision_value\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Space explorer",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "rawSql": "  SELECT  \n  split_part(substring(supervision_namespace, position('/' in supervision_label)), '/', 1) as level_1,\n  split_part(substring(supervision_namespace, position('/' in supervision_label)), '/', 2) as level_2,\n  supervision_value as value\n\tFROM supervision_s3\n\tWHERE supervision_label = 'prefix_size'\n\tand supervision_date = (select max(supervision_date) FROM supervision_s3)\n\tand supervision_value > 0"
    }
   ]
  }
 ]
}