name: Build

on: 
    pull_request:
        types: [assigned, opened, reopened]
    push:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v1
          - name: Check if docker images exist
            run: |
              ./gradlew checkDockerImages
          - name: Build
            run: |
              ./gradlew createZip
          - name: Extract version
            id: extract_version
            run: echo "::set-output name=v::$(cat version.properties | grep 'semver' | sed -e 's/^version.semver=//')"
          - name: List all releases
            uses: actions/github-script@0.3.0
            with:
              github-token: ${{secrets.TOKEN_GITHUB}}
              script: |
                const result = await github.repos.listReleases(context.repo);
                result.data
                  .filter(release => release.tag_name == "${{ steps.extract_version.outputs.v }}")
                  .forEach(function(release){
                    const releaseObj = {release_id:release.id, owner:context.repo.owner, repo:context.repo.repo}
                    github.repos.deleteRelease(releaseObj)
                  });
          - name: Create Release
            id: create_release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
            with:
                tag_name: ${{ steps.extract_version.outputs.v }}
                release_name: Release ${{ steps.extract_version.outputs.v }}
                draft: false
                prerelease: true
          - name: Upload Release technologies Asset ZIP
            id: upload-release-asset-technologies-zip
            uses: actions/upload-release-asset@v1.0.1
            env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB}}
            with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./dist/technologies.zip
              asset_name: technologies.zip
              asset_content_type: application/zip